services:
    terminal42_url_rewrite.rewrite_controller:
        class: Terminal42\UrlRewriteBundle\Controller\RewriteController
        public: true
        arguments:
            - "@terminal42_url_rewrite.provider"
            - "@contao.framework"

    terminal42_url_rewrite.rewrite_loader:
        class: Terminal42\UrlRewriteBundle\Routing\UrlRewriteLoader
        arguments:
            - "@terminal42_url_rewrite.provider"
        tags:
            - { name: routing.loader }

    terminal42_url_rewrite.provider:
        alias: terminal42_url_rewrite.provider.chain

    terminal42_url_rewrite.provider.bundle:
        class: Terminal42\UrlRewriteBundle\ConfigProvider\BundleConfigProvider
        public: false
        tags:
            - { name: terminal42_url_rewrite.provider, priority: 64 }

    terminal42_url_rewrite.provider.chain:
        class: Terminal42\UrlRewriteBundle\ConfigProvider\ChainConfigProvider
        public: false

    terminal42_url_rewrite.provider.database:
        class: Terminal42\UrlRewriteBundle\ConfigProvider\DatabaseConfigProvider
        public: false
        arguments:
            - "@database_connection"
        tags:
            - { name: terminal42_url_rewrite.provider, priority: 32 }

    terminal42_url_rewrite.command.convert_short_urls:
        class: Terminal42\UrlRewriteBundle\Command\ConvertShortUrlsCommand
        public: false
        arguments:
            - "@database_connection"
            - "@terminal42_url_rewrite.listener.rewrite_container"
        tags:
            - { name: console.command }
